// This file is auto-generated by "yarn i18n"
// Do NOT modify this file directly.

export const enum CE_Locale {
    /**
     * Value: Home;
     * Description: A title for home page;
     */
    HOME_PAGE_TITLE = 0x0,

    /**
     * Value: Sign in;
     * Description: A text for sign in page title and button;
     */
    SIGN_IN_TITLE = 0x1,

    /**
     * Value: Sign up;
     * Description: A text for sign up page title and button;
     */
    SIGN_UP_TITLE = 0x2,
}
